"""
XDF generator — produces TunerPro XDF v1.60 XML.

Supported element types
  scalar  → XDFCONSTANT  (single-value parameter)
  1d      → XDFTABLE with X + Z axes  (curve / 1-D lookup)
  2d      → XDFTABLE with X + Y + Z axes  (map / 2-D lookup)
  flag    → XDFFLAG  (single bit or byte mask)
"""

import xml.etree.ElementTree as ET
from typing import Any, Dict, List


class XDFGenerator:
    def __init__(self, config: Dict[str, Any]) -> None:
        self.config = config
        self._uid = 1

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _next_uid(self) -> str:
        uid = f"0x{self._uid:X}"
        self._uid += 1
        return uid

    @staticmethod
    def _parse_addr(addr: Any) -> int:
        if isinstance(addr, int):
            return addr
        s = str(addr).strip()
        return int(s, 16) if s.lower().startswith("0x") else int(s)

    @staticmethod
    def _type_flags(table: Dict) -> int:
        flags = 0
        if table.get("signed", False):
            flags |= 0x01
        if table.get("lsb_first", False):
            flags |= 0x02
        return flags

    @staticmethod
    def _indent(elem: ET.Element, level: int = 0) -> None:
        pad = "\n" + "  " * level
        if len(elem):
            if not elem.text or not elem.text.strip():
                elem.text = pad + "  "
            for child in elem:
                XDFGenerator._indent(child, level + 1)
            if not child.tail or not child.tail.strip():   # type: ignore[union-attr]
                child.tail = pad                           # type: ignore[union-attr]
        if level and (not elem.tail or not elem.tail.strip()):
            elem.tail = pad

    # ------------------------------------------------------------------
    # Entry point
    # ------------------------------------------------------------------

    def generate(self) -> str:
        root = ET.Element("XDFFORMAT")
        root.set("version", "1.60")

        self._add_header(root)

        for item in self.config.get("tables", []):
            kind = item.get("type", "scalar")
            if kind == "scalar":
                self._add_scalar(root, item)
            elif kind == "1d":
                self._add_1d_table(root, item)
            elif kind == "2d":
                self._add_2d_table(root, item)
            elif kind == "flag":
                self._add_flag(root, item)

        self._indent(root)
        xml_body = ET.tostring(root, encoding="unicode")
        return '<?xml version="1.0" encoding="UTF-8"?>\n<!DOCTYPE xdf>\n' + xml_body

    # ------------------------------------------------------------------
    # Header
    # ------------------------------------------------------------------

    def _add_header(self, root: ET.Element) -> None:
        hdr = ET.SubElement(root, "XDFHEADER")

        ET.SubElement(hdr, "flags").text = "0x1"
        ET.SubElement(hdr, "deftitle").text = self.config.get("title", "Generated XDF")
        ET.SubElement(hdr, "description").text = self.config.get(
            "description", "Generated by EcuXDFGenerator"
        )
        ET.SubElement(hdr, "author").text = self.config.get("author", "EcuXDFGenerator")

        bo = ET.SubElement(hdr, "baseoffset")
        bo.set("offset", "0")
        bo.set("subtract", "0")

        dfl = ET.SubElement(hdr, "DEFAULTS")
        dfl.set("datasizeinbits", str(self.config.get("default_size", 8)))
        dfl.set("sigdigits", str(self.config.get("sig_digits", 6)))
        dfl.set("outputtype", "1")
        dfl.set("signed", "0")
        dfl.set("lsbfirst", "1" if self.config.get("lsb_first", False) else "0")
        dfl.set("float", "0")

        reg = ET.SubElement(hdr, "REGION")
        reg.set("type", "0xFFFFFFFF")
        reg.set("startaddress", "0x0")
        reg.set("size", hex(self.config.get("file_size", 0x100000)))
        reg.set("regionflags", "0x0")
        reg.set("name", "Binary File")
        reg.set("desc", "The binary image file edited by this XDF")

        for i, cat in enumerate(self.config.get("categories", [])):
            c = ET.SubElement(hdr, "CATEGORY")
            c.set("index", hex(i))
            c.set("name", cat)

    # ------------------------------------------------------------------
    # Scalar → XDFCONSTANT
    # ------------------------------------------------------------------

    def _add_scalar(self, root: ET.Element, tbl: Dict) -> None:
        param = ET.SubElement(root, "XDFCONSTANT")
        param.set("uniqueid", self._next_uid())
        param.set("flags", "0xC")

        ET.SubElement(param, "title").text = tbl.get("title", "Parameter")
        ET.SubElement(param, "description").text = tbl.get("description", "")

        for cat_idx in tbl.get("categories", []):
            cm = ET.SubElement(param, "CATEGORYMEM")
            cm.set("index", "0")
            cm.set("category", hex(cat_idx))

        addr = self._parse_addr(tbl.get("address", "0x0"))
        elem_size = int(tbl.get("element_size", 8))

        embed = ET.SubElement(param, "EMBEDDEDDATA")
        embed.set("mmedaddress", f"0x{addr:X}")
        embed.set("mmedelementsizebits", str(elem_size))
        embed.set("mmedmajorstridebits", "0")
        embed.set("mmedminorstridebits", "0")
        tf = self._type_flags(tbl)
        if tf:
            embed.set("mmedtypeflags", hex(tf))

        ET.SubElement(param, "units").text = tbl.get("units", "")

        math_el = ET.SubElement(param, "MATH")
        math_el.set("equation", tbl.get("math", "X"))
        ET.SubElement(math_el, "VAR").set("id", "X")

    # ------------------------------------------------------------------
    # 1-D table → XDFTABLE (X + Z axes)
    # ------------------------------------------------------------------

    def _add_1d_table(self, root: ET.Element, tbl: Dict) -> None:
        el = ET.SubElement(root, "XDFTABLE")
        el.set("uniqueid", self._next_uid())
        el.set("flags", "0x0")

        ET.SubElement(el, "title").text = tbl.get("title", "1D Table")
        ET.SubElement(el, "description").text = tbl.get("description", "")

        count = int(tbl.get("count", 16))
        elem_size = int(tbl.get("element_size", 8))
        x_elem_size = int(tbl.get("x_element_size", elem_size))

        # X axis (breakpoints / input axis)
        x_addr = self._parse_addr(tbl.get("x_address", "0x0"))
        x_ax = ET.SubElement(el, "XDFAXIS")
        x_ax.set("id", "x")
        x_ax.set("uniqueid", self._next_uid())
        x_ax.set("flags", "0x0")
        x_emb = ET.SubElement(x_ax, "EMBEDDEDDATA")
        x_emb.set("mmedelementsizebits", str(x_elem_size))
        x_emb.set("mmedaddress", f"0x{x_addr:X}")
        x_emb.set("mmedrowcount", "1")
        x_emb.set("mmedcolcount", str(count))
        x_emb.set("mmedmajorstridebits", str(x_elem_size))
        x_emb.set("mmedminorstridebits", "0")
        ET.SubElement(x_ax, "indexcount").text = str(count)
        ET.SubElement(x_ax, "datatype").text = "0"
        ET.SubElement(x_ax, "unittype").text = "0"
        ET.SubElement(x_ax, "DALINK").set("index", "0")
        x_math = ET.SubElement(x_ax, "MATH")
        x_math.set("equation", tbl.get("x_math", "X"))
        ET.SubElement(x_math, "VAR").set("id", "X")

        # Z axis (output / data values)
        z_addr = self._parse_addr(tbl.get("z_address", tbl.get("address", "0x0")))
        z_ax = ET.SubElement(el, "XDFAXIS")
        z_ax.set("id", "z")
        z_ax.set("uniqueid", self._next_uid())
        z_ax.set("flags", "0x0")
        z_emb = ET.SubElement(z_ax, "EMBEDDEDDATA")
        z_emb.set("mmedelementsizebits", str(elem_size))
        z_emb.set("mmedaddress", f"0x{z_addr:X}")
        z_emb.set("mmedrowcount", "1")
        z_emb.set("mmedcolcount", str(count))
        z_emb.set("mmedmajorstridebits", str(elem_size))
        z_emb.set("mmedminorstridebits", "0")
        tf = self._type_flags(tbl)
        if tf:
            z_emb.set("mmedtypeflags", hex(tf))
        ET.SubElement(z_ax, "indexcount").text = str(count)
        ET.SubElement(z_ax, "datatype").text = "0"
        ET.SubElement(z_ax, "unittype").text = "0"
        ET.SubElement(z_ax, "DALINK").set("index", "0")
        z_math = ET.SubElement(z_ax, "MATH")
        z_math.set("equation", tbl.get("math", "X"))
        ET.SubElement(z_math, "VAR").set("id", "X")

    # ------------------------------------------------------------------
    # 2-D table → XDFTABLE (X + Y + Z axes)
    # ------------------------------------------------------------------

    def _add_2d_table(self, root: ET.Element, tbl: Dict) -> None:
        el = ET.SubElement(root, "XDFTABLE")
        el.set("uniqueid", self._next_uid())
        el.set("flags", "0x30")

        ET.SubElement(el, "title").text = tbl.get("title", "2D Table")
        ET.SubElement(el, "description").text = tbl.get("description", "")

        rows = int(tbl.get("rows", 16))
        cols = int(tbl.get("cols", 16))
        elem_size = int(tbl.get("element_size", 8))
        x_elem_size = int(tbl.get("x_element_size", elem_size))
        y_elem_size = int(tbl.get("y_element_size", elem_size))

        # X axis (column headers)
        x_addr = self._parse_addr(tbl.get("x_address", "0x0"))
        x_ax = ET.SubElement(el, "XDFAXIS")
        x_ax.set("id", "x")
        x_ax.set("uniqueid", self._next_uid())
        x_ax.set("flags", "0x0")
        x_emb = ET.SubElement(x_ax, "EMBEDDEDDATA")
        x_emb.set("mmedelementsizebits", str(x_elem_size))
        x_emb.set("mmedaddress", f"0x{x_addr:X}")
        x_emb.set("mmedrowcount", "1")
        x_emb.set("mmedcolcount", str(cols))
        x_emb.set("mmedmajorstridebits", str(x_elem_size))
        x_emb.set("mmedminorstridebits", "0")
        ET.SubElement(x_ax, "indexcount").text = str(cols)
        ET.SubElement(x_ax, "datatype").text = "0"
        ET.SubElement(x_ax, "unittype").text = "0"
        ET.SubElement(x_ax, "DALINK").set("index", "0")
        x_math = ET.SubElement(x_ax, "MATH")
        x_math.set("equation", tbl.get("x_math", "X"))
        ET.SubElement(x_math, "VAR").set("id", "X")

        # Y axis (row headers)
        y_addr = self._parse_addr(tbl.get("y_address", "0x0"))
        y_ax = ET.SubElement(el, "XDFAXIS")
        y_ax.set("id", "y")
        y_ax.set("uniqueid", self._next_uid())
        y_ax.set("flags", "0x0")
        y_emb = ET.SubElement(y_ax, "EMBEDDEDDATA")
        y_emb.set("mmedelementsizebits", str(y_elem_size))
        y_emb.set("mmedaddress", f"0x{y_addr:X}")
        y_emb.set("mmedrowcount", str(rows))
        y_emb.set("mmedcolcount", "1")
        y_emb.set("mmedmajorstridebits", str(y_elem_size))
        y_emb.set("mmedminorstridebits", "0")
        ET.SubElement(y_ax, "indexcount").text = str(rows)
        ET.SubElement(y_ax, "datatype").text = "0"
        ET.SubElement(y_ax, "unittype").text = "0"
        ET.SubElement(y_ax, "DALINK").set("index", "0")
        y_math = ET.SubElement(y_ax, "MATH")
        y_math.set("equation", tbl.get("y_math", "X"))
        ET.SubElement(y_math, "VAR").set("id", "X")

        # Z axis (data values — row-major)
        z_addr = self._parse_addr(tbl.get("address", "0x0"))
        z_ax = ET.SubElement(el, "XDFAXIS")
        z_ax.set("id", "z")
        z_ax.set("uniqueid", self._next_uid())
        z_ax.set("flags", "0x0")
        z_emb = ET.SubElement(z_ax, "EMBEDDEDDATA")
        z_emb.set("mmedelementsizebits", str(elem_size))
        z_emb.set("mmedaddress", f"0x{z_addr:X}")
        z_emb.set("mmedrowcount", str(rows))
        z_emb.set("mmedcolcount", str(cols))
        z_emb.set("mmedmajorstridebits", str(cols * elem_size))
        z_emb.set("mmedminorstridebits", "0")
        tf = self._type_flags(tbl)
        if tf:
            z_emb.set("mmedtypeflags", hex(tf))
        ET.SubElement(z_ax, "indexcount").text = str(rows * cols)
        ET.SubElement(z_ax, "datatype").text = "0"
        ET.SubElement(z_ax, "unittype").text = "0"
        ET.SubElement(z_ax, "DALINK").set("index", "0")
        z_math = ET.SubElement(z_ax, "MATH")
        z_math.set("equation", tbl.get("math", "X"))
        ET.SubElement(z_math, "VAR").set("id", "X")

    # ------------------------------------------------------------------
    # Bit flag → XDFFLAG
    # ------------------------------------------------------------------

    def _add_flag(self, root: ET.Element, tbl: Dict) -> None:
        el = ET.SubElement(root, "XDFFLAG")
        el.set("uniqueid", self._next_uid())
        el.set("flags", "0x0")

        ET.SubElement(el, "title").text = tbl.get("title", "Flag")
        ET.SubElement(el, "description").text = tbl.get("description", "")

        addr = self._parse_addr(tbl.get("address", "0x0"))
        elem_size = int(tbl.get("element_size", 8))

        embed = ET.SubElement(el, "EMBEDDEDDATA")
        embed.set("mmedaddress", f"0x{addr:X}")
        embed.set("mmedelementsizebits", str(elem_size))
        embed.set("mmedmajorstridebits", "0")
        embed.set("mmedminorstridebits", "0")

        ET.SubElement(el, "mask").text = tbl.get("mask", "0x1")
