"""ECU profiles with known checksums, sizes, and common table hints."""

ECU_PROFILES = [
    {
        "id": "subaru_ej_1mb",
        "name": "Subaru EJ 1MB (WRX / STI)",
        "binary_sizes": [0x100000],
        "description": "Subaru WRX / STI EJ20 / EJ25 — 1 MB Denso ECU",
        "endian": "big",
        "checksum": {
            "algorithm": "subaru",
            "region_start": "0x0",
            "region_end": "0xFFFC",
            "storage_address": "0xFFFC",
            "storage_size": 4,
        },
        "default_categories": ["Fuel", "Timing", "Boost", "Idle", "Misc"],
        "known_tables": [
            {
                "title": "Primary Fuel Map",
                "type": "2d",
                "description": "Primary fuel map — injector pulse width vs RPM / Load",
                "rows": 20,
                "cols": 20,
                "element_size": 8,
                "units": "ms",
                "math": "X*0.016667",
                "x_math": "X*100",
                "y_math": "X*0.5",
            },
        ],
    },
    {
        "id": "subaru_ej_512kb",
        "name": "Subaru EJ 512 KB",
        "binary_sizes": [0x80000],
        "description": "Older Subaru EJ ECU — 512 KB Denso",
        "endian": "big",
        "checksum": {
            "algorithm": "subaru",
            "region_start": "0x0",
            "region_end": "0x7FFFC",
            "storage_address": "0x7FFFC",
            "storage_size": 4,
        },
        "default_categories": ["Fuel", "Timing", "Boost", "Idle", "Misc"],
        "known_tables": [],
    },
    {
        "id": "honda_obd1_256kb",
        "name": "Honda OBD1 256 KB (P28 / P30 / P72)",
        "binary_sizes": [0x40000],
        "description": "Honda OBD1 ECU — 256 KB (Civic / Integra)",
        "endian": "big",
        "checksum": {
            "algorithm": "honda",
            "region_start": "0x0",
            "region_end": "0x3FFFF",
            "storage_address": "0x3FFFF",
            "storage_size": 1,
        },
        "default_categories": ["Fuel", "Timing", "VTEC", "Idle", "Misc"],
        "known_tables": [],
    },
    {
        "id": "honda_obd2_512kb",
        "name": "Honda OBD2 512 KB",
        "binary_sizes": [0x80000],
        "description": "Honda OBD2 ECU — 512 KB",
        "endian": "big",
        "checksum": {
            "algorithm": "honda",
            "region_start": "0x0",
            "region_end": "0x7FFFF",
            "storage_address": "0x7FFFF",
            "storage_size": 1,
        },
        "default_categories": ["Fuel", "Timing", "VTEC", "Idle", "Misc"],
        "known_tables": [],
    },
    {
        "id": "mitsubishi_evo_1mb",
        "name": "Mitsubishi EVO 1 MB",
        "binary_sizes": [0x100000],
        "description": "Mitsubishi EVO VIII / IX — 1 MB ECU",
        "endian": "little",
        "checksum": {
            "algorithm": "crc32",
            "region_start": "0x0",
            "region_end": "0xFFFC",
            "storage_address": "0xFFFC",
            "storage_size": 4,
        },
        "default_categories": ["Fuel", "Timing", "Boost", "Idle", "Misc"],
        "known_tables": [],
    },
    {
        "id": "generic_1mb",
        "name": "Generic 1 MB ECU",
        "binary_sizes": [0x100000],
        "description": "Generic / unknown manufacturer — 1 MB binary",
        "endian": "big",
        "checksum": {
            "algorithm": "sum32",
            "region_start": "0x0",
            "region_end": "0xFFFC",
            "storage_address": "0xFFFC",
            "storage_size": 4,
        },
        "default_categories": ["Fuel", "Timing", "Boost", "Idle", "Misc"],
        "known_tables": [],
    },
    {
        "id": "generic_512kb",
        "name": "Generic 512 KB ECU",
        "binary_sizes": [0x80000],
        "description": "Generic / unknown manufacturer — 512 KB binary",
        "endian": "big",
        "checksum": {
            "algorithm": "sum32",
            "region_start": "0x0",
            "region_end": "0x7FFFC",
            "storage_address": "0x7FFFC",
            "storage_size": 4,
        },
        "default_categories": ["Fuel", "Timing", "Misc"],
        "known_tables": [],
    },
    {
        "id": "generic_256kb",
        "name": "Generic 256 KB ECU",
        "binary_sizes": [0x40000],
        "description": "Generic / unknown manufacturer — 256 KB binary",
        "endian": "big",
        "checksum": {
            "algorithm": "sum16",
            "region_start": "0x0",
            "region_end": "0x3FFFE",
            "storage_address": "0x3FFFE",
            "storage_size": 2,
        },
        "default_categories": ["Fuel", "Timing", "Misc"],
        "known_tables": [],
    },
]
